# Generated by Django 5.1.1 on 2024-10-17 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("task_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "task_tag",
                    models.CharField(
                        choices=[
                            ("Learning", "Learning"),
                            ("Life", "Life"),
                            ("Job", "Job"),
                        ],
                        max_length=20,
                    ),
                ),
                ("task_title", models.CharField(max_length=200)),
                ("task_description", models.TextField()),
                (
                    "task_status",
                    models.CharField(
                        choices=[
                            ("awaiting", "Awaiting"),
                            ("ongoing", "Ongoing"),
                            ("finished", "Finished"),
                            ("aborted", "Aborted"),
                        ],
                        default="awaiting",
                        max_length=20,
                    ),
                ),
                ("reward_points", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deadline", models.DateTimeField()),
                ("is_reviewed", models.BooleanField(default=False)),
                (
                    "assignee_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to="users.user",
                    ),
                ),
                (
                    "creator_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tasks",
                        to="users.user",
                    ),
                ),
            ],
        ),
    ]
