# Generated by Django 5.1.1 on 2024-10-24 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_task_assignee_id_alter_task_creator_id"),
        ("users", "0002_user_is_alive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assignee_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tasks",
                to="users.user",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="creator_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_tasks",
                to="users.user",
            ),
        ),
    ]
