# Generated by Django 5.1.1 on 2024-10-24 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_alter_task_assignee_id_alter_task_creator_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="assignee_id",
            new_name="assignee",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="creator_id",
            new_name="creator",
        ),
    ]
