# Generated by Django 5.1.1 on 2024-10-24 12:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_rename_assignee_id_task_assignee_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="assignee",
            new_name="assignee_id",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="creator",
            new_name="creator_id",
        ),
    ]
