# Generated by Django 5.1.1 on 2024-10-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("nickname", models.CharField(max_length=100)),
                ("password_hash", models.CharField(max_length=256)),
                ("user_introduction", models.TextField()),
                ("credit_score", models.IntegerField(default=0)),
                ("remaining_points", models.IntegerField(default=0)),
                ("ability_score", models.IntegerField(default=0)),
            ],
        ),
    ]
